routes/web.php
<?php
//URL::forceScheme('https');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/coin/{coin_name}','CoinController@show')->name('coin.name');

Route::middleware(['auth'])->group(function () {

    Route::get('/admin/login', 'Auth\LoginController@login')->name('admin.login');

    Route::get('/home', 'CoinController@index')->name('home');

    Route::resource('coins','CoinController');

    Route::get('/coin/social/{id}','CoinController@social')->name('coin.social');
    Route::post('/coin/social/store','CoinController@social_store')->name('social.store');
    Route::post('/coin/social/update/{id}','CoinController@social_update')->name('social.update');

});

resources/views/create_coin.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-8 offset-2">
    @include('layouts.alerts')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add New Coin</h3>
        </div>
        <div class="block-content">
            <form action="{!! route('coins.store') !!}" method="post">
                @csrf
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="name">Coin Name</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Coin Name" value="{{ \Request::old('name') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="ticker">Coin Ticker</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="ticker" name="ticker" placeholder="Enter Coin's Ticker" value="{{ \Request::old('ticker') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="paid_rewards_mn">Paid Rewards For Masternodes</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="paid_rewards_mn" name="paid_rewards_mn" placeholder="Enter Paid Rewards For Masternodes" value="{{ \Request::old('paid_rewards_mn') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_required_coins">MasterNode Required Coins</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_required_coins" name="mn_required_coins" placeholder="MasterNode Required Coins" value="{{ \Request::old('mn_required_coins') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="icon_url">Icon URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="icon_url" name="icon_url" placeholder="Enter Coin's Icon URL" value="{{ \Request::old('icon_url') }}">
                    </div>
                </div>
                {{-- MN Info--}}
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="masternode_reward_per_block">Masternode Reward Per Block</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="masternode_reward_per_block" name="masternode_reward_per_block" placeholder="Enter Coin's Masternode Reward Per Block" value="{{ \Request::old('masternode_reward_per_block') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="block_time">Block Time (second)</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="block_time" name="block_time" placeholder="Enter Coin's Block Time (second)" value="{{ \Request::old('block_time') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="algorithm">Coin Algorithm</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="block_time" name="algorithm" placeholder="Enter Coin's Algorithm" value="{{ \Request::old('algorithm') }}">
                    </div>
                </div>
                {{-- Deamon Info--}}
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="rpc_host">Deamon Host</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="rpc_host" name="rpc_host" placeholder="Enter Coin's Deamon Host"  value="{{ \Request::old('rpc_host') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="rpc_port">Deamon Port</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="rpc_port" name="rpc_port" placeholder="Enter Coin's Deamon Port" value="{{ \Request::old('rpc_port') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="rpc_user">Deamon User</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="rpc_user" name="rpc_user" placeholder="Enter Coin's Deamon User" value="{{ \Request::old('rpc_user') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="rpc_password">Deamon Password</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="rpc_password" name="rpc_password" placeholder="Enter Coin's Deamon Password" value="{{ \Request::old('rpc_password') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-9 ml-auto">
                        <a href="{!! route('coins.index') !!}" class="btn btn-alt-danger offset-5"> Back</a>
                        <button type="submit" class="btn btn-alt-primary offset-1"> Add</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@endsection

resources/views/create_social.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-8 offset-2">
    @include('layouts.alerts')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Social Media</h3>
        </div>

        <div class="block-content">
            <form action="{!! isset($coin->social) ? route('social.update',$coin->social->id) : route('social.store') !!}" method="post">
                @csrf
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="twitter">Twitter URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Enter Twitter URL" value="{!! isset($coin->social->twitter) ? $coin->social->twitter : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="btc_talk">BitcoinTalk URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="btc_talk" name="btc_talk" placeholder="Enter BitcoinTalk URL" value="{!! isset($coin->social->btc_talk) ? $coin->social->btc_talk : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="explorer">Explorer URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="explorer" name="explorer" placeholder="Enter Explorer URL" value="{!! isset($coin->social->explorer) ? $coin->social->explorer : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="github">Github URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="github" name="github" placeholder="Enter Github URL" value="{!! isset($coin->social->github) ? $coin->social->github : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="website">Website URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="website" name="website" placeholder="Enter Website URL" value="{!! isset($coin->social->website) ? $coin->social->website : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange1">Excange URL 1</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange1" name="exchange1" placeholder="Enter Excange URL 1" value="{!! isset($coin->social->exchange1) ? $coin->social->exchange1 : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange1">Excange Name 1</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange_name1" name="exchange_name1" placeholder="Enter Excange Name 1" value="{!! isset($coin->social->exchange_name1) ? $coin->social->exchange_name1 : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange2">Excange URL 2</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange2" name="exchange2" placeholder="Enter Excange URL 2" value="{!! isset($coin->social->exchange2) ? $coin->social->exchange2 : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange_name2">Excange URL 2</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange_name2" name="exchange_name2" placeholder="Enter Excange Name 2" value="{!! isset($coin->social->exchange_name2) ? $coin->social->exchange_name2 : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange3">Excange URL 3</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange3" name="exchange3" placeholder="Enter Excange URL 3" value="{!! isset($coin->social->exchange3) ? $coin->social->exchange3 : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange_name3">Excange Name 3</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange_name3" name="exchange_name3" placeholder="Enter Excange Name 3" value="{!! isset($coin->social->exchange_name3) ? $coin->social->exchange_name3 : null !!}">
                    </div>
                </div>
                <input type="hidden" name="coin_name" value="{!! $coin->name !!}">
                <input type="hidden" name="coin_id" value="{!! $coin->id !!}">
                <div class="form-group row">
                    <div class="col-lg-9 ml-auto">
                        <a href="{!! route('coins.index') !!}" class="btn btn-alt-danger offset-5"> Back</a>
                        <button type="submit" class="btn btn-alt-primary offset-1"> Add</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@endsection

resources/views/edit_coin.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-8 offset-2">
    @include('layouts.alerts')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add New Coin</h3>
        </div>
        <div class="block-content">
            <form action="{!! route('coins.update',$coin->id) !!}" method="post">
                @csrf @method('PUT')
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="name">Coin Name</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Coin Name" value="{!! $coin->name !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="ticker">Coin Ticker</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="ticker" name="ticker" placeholder="Enter Coin's Ticker" value="{!! $coin->ticker !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange_api_url">Exchange API URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange_api_url" name="exchange_api_url" placeholder="Enter Exchange API URL" value="{!! $coin->exchange_api_url !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="paid_rewards_mn">Paid Rewards For Masternodes</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="paid_rewards_mn" name="paid_rewards_mn" placeholder="Enter Paid Rewards For Masternodes" value="{!! $coin->paid_rewards_mn !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_required_coins">MasterNode Required Coins</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_required_coins" name="mn_required_coins" placeholder="MasterNode Required Coins" value="{!! $coin->mn_required_coins !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="circulation_supply_api_url">Circulation Supply API URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="circulation_supply_api_url" name="circulation_supply_api_url" placeholder="Enter Circulation Supply API URL" value="{!! $coin->circulation_supply_api_url !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_count_api_url">MasterNode Count API URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_count_api_url" name="mn_count_api_url" placeholder="Enter MasterNode Count API URL" value="{!! $coin->mn_count_api_url !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="icon_url">Icon URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="icon_url" name="icon_url" placeholder="Enter Coin's Icon URL" value="{!! $coin->icon_url !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-9 ml-auto">
                        <a href="{!! route('coins.index') !!}" class="btn btn-alt-danger offset-5"> Back</a>
                        <button type="submit" class="btn btn-alt-primary offset-1"> Edit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.alerts')
    <div class="row">
        <div class="col-12">
            <a href="{!! route('coins.create') !!}" class="btn btn-success float-right">
                <i class="fa fa-plus-circle"></i> Add New Coin
            </a>
        </div>
    </div>
    <br>
    <div id="DataTables_Table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-striped table-vcenter js-dataTable-full dataTable no-footer" id="DataTables_Table_1" role="grid">
                    <thead>
                    <tr role="row">
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1"
                            colspan="1" aria-label="Name: activate to sort column ascending">Name
                        </th>
                        <th class="d-none d-sm-table-cell sorting" tabindex="0"
                            aria-controls="DataTables_Table_1" rowspan="1" colspan="1">
                            VOLUME
                        </th>
                        <th class="d-none d-sm-table-cell sorting_desc" style="width: 15%;" tabindex="0"
                            aria-controls="DataTables_Table_1" rowspan="1" colspan="1"
                            aria-label="Access: activate to sort column ascending" aria-sort="descending">
                            MARKET CAP
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">PRICE
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">CHANGE
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">ROI
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">MN WORTH
                        </th>
                        <td>
                            Action
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                @if(isset($coins) && count($coins))
                    @foreach($coins as $coin)
                        <tr role="row" class="odd">
                            <td class="text-center"><img src="{!! $coin->icon_url !!}" alt="{!! $coin->name !!}" width="20"> <strong>{!! $coin->name !!}</strong>   </td>
                            <td class="font-w600">{!! number_format((float)$usd_24h_vol[$coin->name], 2, '.', ',') !!} $</td>
                            <td class="d-none d-sm-table-cell">{!! number_format((float)$market_cap[$coin->name], 2, '.', ',') !!} $</td>
                            <td class="d-none d-sm-table-cell">{!! $usd[$coin->name] !!} $</td>
                            <td class="d-none d-sm-table-cell"> <span style="color: {!! $usd_24h_change[$coin->name] < 0 ? 'red' : 'green' !!}">% {!! number_format((float)$usd_24h_change[$coin->name], 2, '.', ',') !!} <i class="fa fa-angle-double-{!! $usd_24h_change[$coin->name] < 0 ? 'down' : 'up' !!}"></i> </span></td>
                            <td class="d-none d-sm-table-cell">{!! number_format((float)$roi_percent[$coin->name], 2, '.', ',').' % / '.(int)$roi_days[$coin->name] !!} Days</td>
                            <td class="d-none d-sm-table-cell">{!! number_format((float)$mn_worth[$coin->name], 3, '.', ',') !!} $</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <a href="{!! route('coins.edit',$coin->id) !!}" class="btn btn-sm btn-secondary js-tooltip-enabled" data-toggle="tooltip" title="Edit" data-original-title="Edit">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <form action="{!! route('coins.destroy',$coin->id) !!}" method="POST">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-secondary js-tooltip-enabled" data-toggle="tooltip" title="Delete" data-original-title="Delete">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </form>
                                    <a href="{!! route('coin.social',$coin->id) !!}" class="btn btn-sm btn-secondary js-tooltip-enabled" data-toggle="tooltip" title="Social Media" data-original-title="Social">
                                        <i class="fa fa-link"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
          </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection